map $request_method $limit {
    default "";
    POST $binary_remote_addr;
}

limit_req_zone $limit zone=timeline_limit:10m rate=1r/m;

server {
    listen 80;
    listen [::]:80;
    server_name saiborg.duckdns.org;

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name saiborg.duckdns.org;

    ssl_certificate         /etc/letsencrypt/live/saiborg.duckdns.org/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/saiborg.duckdns.org/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/saiborg.duckdns.org/chain.pem;
    ssl_dhparam             /etc/letsencrypt/dhparams/dhparam.pem;

    location /api/timeline_post {
        limit_req zone=timeline_limit burst=0 nodelay;
        limit_req_status 429;

        proxy_pass http://myportfolio:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }

    location / {
        proxy_pass http://myportfolio:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }
}
